[project]
name = "voice-model-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aaina Batool", email = "b.aaina@yahoo.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
voice-model-playground = "voice_model_playground:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
